# Generated by Django 5.0.3 on 2024-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_movie_remove_user_movieid_user_movieids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movieIDs',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='myapp.movie'),
        ),
    ]
