# Generated by Django 5.0.3 on 2024-04-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_movie_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
