# Generated by Django 5.0.3 on 2024-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_movie_movieid_alter_user_movieids'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
