# Generated by Django 5.0.3 on 2024-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movieID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
