# Generated by Django 5.0.3 on 2024-04-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movieIDs',
        ),
        migrations.AddField(
            model_name='user',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myapp.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='guest', max_length=15, unique=True),
        ),
    ]
