# Generated by Django 5.0.3 on 2024-04-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_user_movieids_user_movie_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='movie',
            new_name='movieIDs',
        ),
    ]
