# Generated by Django 5.0.3 on 2024-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_movie_user_movieids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='user',
            name='movieIDs',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='guest', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='movieIDs',
            field=models.ManyToManyField(blank=True, related_name='users', to='myapp.movie'),
        ),
    ]
