# Generated by Django 5.0.3 on 2024-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_user_email_remove_user_movieids_user_movieids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='user',
            name='movieIDs',
        ),
        migrations.AddField(
            model_name='user',
            name='movieIDs',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='myapp.movie'),
        ),
    ]
