# Generated by Django 5.0.3 on 2024-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_user_email_remove_user_movieids_user_movieids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='movieIDs',
            field=models.ManyToManyField(blank=True, default=list, null=True, related_name='users', to='myapp.movie'),
        ),
    ]
